### ISSUE TITLE
Is SETTINGS frame on HTTP/3 control stream allowed if there is a SETTINGS frame in ALPS?

### ISSUE THREAD

**Issue by bencebeky** [vasilvv/httpbis-alps#2]
Section 3, "Use of ALPS in HTTP", makes a SETTINGS frame in ALPS "supersede the requirement to send a SETTINGS frame at the beginning of the HTTP/2 connection", which makes perfect sense.  The way I interpret "superseding the requirement" is that it is not required, but there is no prohibition on sending further SETTINGS frames on stream 0, which is fine for HTTP/2.

However, in case of HTTP/3, a SETTINGS frame in ALPS "supersedes the requirement to send a SETTINGS frame at the beginning of the control stream".  It does not explicitly ban a SETTINGS frame as the first frame on the control stream, and does not explicitly mention if the ban on sending a SETTINGS frame as the non-first frame on the control stream is affected.  I propose that we spell out explicitly that in case a SETTINGS frame in sent in ALPS, no SETTINGS frames MUST be sent on the control stream.  This is in alignment with HTTP/3's requirement that there must be exactly one SETTINGS frame.

**Comment by davidben** [comment]
One extra complication here is things like GREASE and ALPS preferring the values not changed much (see issue #4). We can model the proposal in #4 in h2 by saying you're still allowed to send more SETTINGS frames if you like. In h3, this gets tricky.

If we like the #4 proposal (do we?),  perhaps we say that h3 is still obligated to send in-band SETTINGS, but it can be empty? @vasilvv, what do you think?

**Comment by bencebeky** [comment]
I'm concerned that some existing HTTP/3 implementations might have it baked in that the value of a setting parameter cannot change (other than from default when receiving the first and only SETTINGS frame).  Or that the spec does not specify how to deal with that, for example, QPACK_MAX_TABLE_CAPACITY really must not change, because it would mess with dynamic table indexing.

If we allow or require a SETTINGS frame on the control stream even if there was one in ALPS, should we consider requiring that the setting parameters do not overlap between the two?  (Of course empty would be a special case of that.)  This would leave room for GREASE on the control stream.

**Comment by davidben** [comment]
I think HTTP/3 may already have gone down that route with 0-RTT. 0-RTT changes the initial values of the SETTINGS values and then the server gets one shot to change it again.

(ALPS came about because we weren't very happy with HTTP/3's 0-RTT / NewSessionTicket integration and this seemed a more principled way to do it.)

**Comment by bencebeky** [comment]
Oh okay, you are right.  Note that there are special provisions for this case: " If 0-RTT data is accepted by the server, its SETTINGS frame MUST NOT reduce any limits or alter any values that might be violated by the client with its 0-RTT data." in HTTP/3 7.2.4.2, and "When the client's 0-RTT value of the SETTING [...] is non-zero, the server MUST send the same non-zero value in its SETTINGS frame." in QPACK 3.2.3.  If we decide not to ban control stream SETTINGS from overriding ALPS SETTINGS, we might want to consider copying these requirements or stating that whatever requirements exist for 0-RTT remembered data apply as well.

**Comment by davidben** [comment]
Yeah. TBH, there may be something to be said for replacing the non-ALPS version of remembering SETTINGS anyway? The ALPS 0-RTT integration does the same thing. (Just that ALPS also gives us a clear ordering while h3 as-is doesn't guarantee half-RTT SETTINGS.)

**Comment by vasilvv** [comment]
I feel like it would make more sense to forbid sending the second SETTINGS frame?  I am not sure, either would make sense.  I suspect that people in quic WG might have strong opinion one way or another though.

**Comment by davidben** [comment]
My main worry is, if we forbid sending it, we'll conflict with #4. While we could do it, I'm not a big fan of TLS needing to evaluate an "is setting compatible" function, or draft-thomson-httpbis-h2-0rtt-00's registry idea. Dividing the data up between saved and unsaved bits seems cleaner to me.
